### ISSUE TITLE
Feature Request: Add KMO and Bartlett's test to Factor Analysis

### ISSUE THREAD

**Issue by Suggestions-Only** [jasp-stats/jasp-desktop#1394] opened 2016-08-03 04:44 UTC
I've taken a look at the R code and there doesn't seem to be KMO or Bartlett's for Factor Analysis in JASP.  Since these functions are already available in the psych package for R, I'm hoping it would be relatively simple to add. Thanks!

**Comment by AlexanderLyNL** [comment] 2018-10-11 21:16
Duplicate of #1926

**Closed by AlexanderLyNL** 2018-10-11 21:16 UTC
Labels: Type: Enhancement
