### ISSUE TITLE
Feature Request: copy LaTeX code for tables

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2148] opened 2017-11-09 16:07 UTC
This would be really nice. There aren't many LaTeX users among our target audience, but still, enough people are, and it would make the lives of those people *a lot* easier.
E.J.

**Comment by boutinb** [comment] 2017-12-21 13:16
Duplicate of #2040

**Closed by boutinb** 2017-12-21 13:16 UTC
Labels: Duplicate
