### ISSUE TITLE
JASP v. 0.8.1.1; Win 10; ANOVA; with large data set JASP is stalling. I cannot understand how to attach the file 

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [jasp-stats/jasp-desktop#1791] opened 2017-05-28 19:18 UTC
## Environment (for bugs)

* JASP version:
* OS name and version:
* Analysis:
## Environment (for enhancement requests)
 
* Enhancement:
* Purpose:

**Comment by NikitaKhromov-Borisov** [comment] 2017-05-28 19:29
JASP v. 0.8.1.1; Win 10; ANOVA
I have large data set and JASP is stalled with Post Hoc Tests
![anova](https://cloud.githubusercontent.com/assets/16406847/26531597/da6a0b70-43f4-11e7-8382-3185087daae6.jpg)
[JASP_NK.xlsx](https://github.com/jasp-stats/jasp-desktop/files/1034451/JASP_NK.xlsx)

**Comment by TimKDJ** [comment] 2017-05-31 12:43
Hi @NikitaKhromov-Borisov,

I did some quick descriptives and it appears that your factor has 105 levels.
This totals to 105 choose 2 = 5460 pairwise comparisons.
So if this post-hoc analysis did work, you'd end up with a table containing 5460 rows...
I'm not sure how interpretable that would be.

The R package we use in JASP apparently sets a limit at 1000 comparisons (or 45 levels).
I had a look, but there is no quick solution to this problem. 
In the future we would likely just give a more informative error message.

Cheers,
Tim

**Comment by NikitaKhromov-Borisov** [comment] 2017-05-31 13:21
Dear Tim,

thank you, I will wait the improvements.
Several times I tried to unsinst your collegues to report the actual values
of p-values, not inequality like <0.0001. It's extremly important at least
for their combining and checking their distribution. JASP reports all BFs
as actual values, so p-value should be reported in the same manner. BTW,
please, let JASP presents all thre BFs (BF01, BF10, log(BFs)
simultaniously, like different multiple comparisons, especially for
different models in contingency table analysis (fixed raws, fixed columns,
multinomial, Poisson). Moreover, it would be useful to calculate and presnt
CIs (confidence and/or credible intrvalas) for any effect sizes, e.g.,
contingency coefficients, etc.

Всех благ,
НХ

2017-05-31 15:43 GMT+03:00 Tim de Jong <notifications@github.com>:

**Comment by AlexanderLyNL** [comment] 2017-06-06 15:03
The exact p-value issue is a duplicate of #1802

**Comment by NikitaKhromov-Borisov** [comment] 2017-06-06 16:45
Dear Alexander,
APA "standard" is non-scientific. Exact (real, actual) p-values are needed at least when solving the problem of multiple comparison. In this case testing the uniformity of the p-value distribution is required. 
All BFs present the same information from the matematician point of view, however, from the user's point of view, BF=45.7 looks more vivid and interpretable, then 1/BF=0.021
Cheers,
Nikita

**Comment by AlexanderLyNL** [comment] 2017-06-06 16:53
Dear Nikita,

Thank you for your comments. We agree that exact p-values are more informative and JASP will be able to show these exact values in our next release. 

Cheers,
Alexander

**Comment by NikitaKhromov-Borisov** [comment] 2017-08-05 10:33
Dear Alexander,

It seems there is another bug:
The phi-coefficient in always doesn't calculated.
JASP reports:

ᵃ Value could not be calculated - At least one row or column contains all
zeros
In reality the contingency tables analyzed do not contain such rows or
columns
e.g.,

*Contingency Tables *

*VV *

*BK *

*1 *

*2 *

*3 *

*4 *

*5 *

*Total *

1

2.00

1.00

0.00

0.00

0.00

3.00

2

3.00

25.00

5.00

0.00

1.00

34.00

3

0.00

45.00

7.00

3.00

3.00

58.00

4

0.00

9.00

2.00

7.00

3.00

21.00

5

0.00

10.00

2.00

3.00

1.00

16.00

6

0.00

3.00

3.00

2.00

1.00

9.00

Total

5.00

93.00

19.00

15.00

9.00

141.00

*Chi-Squared Tests *



*Value *

*df *

*p *

*VS-MPR *

Χ²

69.81

20

< .001

121875

Χ² continuity correction

69.81

20

< .001

121875

Likelihood ratio

47.13

20

< .001

87.39

N

141.0

*Chi-Squared Tests *



*Value *

*df *

*p *

*VS-MPR *

Χ²

69.81

20

< .001

121875

Χ² continuity correction

69.81

20

< .001

121875

Likelihood ratio

47.13

20

< .001

87.39

N

141.0



*Nominal *



*Value *

Contingency coefficient

0.575

Phi-coefficient

NaN

ᵃ

Cramer's V

0.352

ᵃ Value could not be calculated - At least one row or column contains all
zeros

Best regards,
Nikita

2017-06-06 19:53 GMT+03:00 AlexanderLyNL <notifications@github.com>:

**Comment by AlexanderLyNL** [comment] 2017-08-15 07:54
Hi Nikita, 

Could you please send us the data file?

Cheers,
Alexander

**Comment by NikitaKhromov-Borisov** [comment] 2017-08-15 08:13
Hi,
these are the data



JASP

*Contingency Tables*

*Contingency Tables *

*PPI *

*Inf *

*1 *

*2 *

*3 *

*Total *

1

1.00

0.00

2.00

3.00

2

5.00

1.00

4.00

10.00

3

5.00

6.00

3.00

14.00

4

2.00

0.00

0.00

2.00

5

1.00

0.00

1.00

2.00

6

1.00

1.00

1.00

3.00

7

1.00

1.00

1.00

3.00

8

1.00

1.00

0.00

2.00

9

0.00

1.00

1.00

2.00

10

1.00

1.00

0.00

2.00

11

0.00

0.00

1.00

1.00

12

0.00

0.00

6.00

6.00

13

2.00

2.00

2.00

6.00

Total

20.00

14.00

22.00

56.00

*Chi-Squared Tests *



*Value *

*df *

*p *

*VS-MPR *

Χ²

25.35

24

0.387

1.000

Χ² continuity correction

25.35

24

0.387

1.000

Likelihood ratio

31.26

24

0.146

1.308

N

56.00



*Nominal *



*Value *

Contingency coefficient

0.558

Phi-coefficient

NaN

ᵃ

Cramer's V

0.476

ᵃ Value could not be calculated - At least one row or column contains all
zeros


Contingency Tables

*Contingency Tables *

*Sex *

*Diag *

*f *

*m *

*Total *

1

176.00

143.00

319.00

2

13.00

32.00

45.00

3

42.00

79.00

121.00

4

70.00

19.00

89.00

5

46.00

27.00

73.00

6

10.00

11.00

21.00

7

3.00

2.00

5.00

8

16.00

21.00

37.00

Total

376.00

334.00

710.00

*Chi-Squared Tests *



*Value *

*df *

*p *

*VS-MPR *

Χ²

55.55

7

< .001

1.544e +7

Χ² continuity correction

55.55

7

< .001

1.544e +7

Likelihood ratio

57.72

7

< .001

3.970e +7

N

710.0



*Nominal *



*Value *

Contingency coefficient

0.269

Phi-coefficient

NaN

ᵃ

Cramer's V

0.280

ᵃ Value could not be calculated - At least one row or column contains all
zeros
Contingency Tables

*Contingency Tables *

*VV *

*BK *

*1 *

*2 *

*3 *

*4 *

*5 *

*Total *

1

2.00

1.00

0.00

0.00

0.00

3.00

2

3.00

25.00

5.00

0.00

1.00

34.00

3

0.00

45.00

7.00

3.00

3.00

58.00

4

0.00

9.00

2.00

7.00

3.00

21.00

5

0.00

10.00

2.00

3.00

1.00

16.00

6

0.00

3.00

3.00

2.00

1.00

9.00

Total

5.00

93.00

19.00

15.00

9.00

141.00

*Chi-Squared Tests *



*Value *

*df *

*p *

*VS-MPR *

Χ²

69.81

20

< .001

121875

Χ² continuity correction

69.81

20

< .001

121875

Likelihood ratio

47.13

20

< .001

87.39

N

141.0



*Nominal *



*Value *

Contingency coefficient

0.575

Phi-coefficient

NaN

ᵃ

Cramer's V

0.352

ᵃ Value could not be calculated - At least one row or column contains all
zeros



Best regards,
Nikita


2017-08-15 10:54 GMT+03:00 AlexanderLyNL <notifications@github.com>:

**Comment by AlexanderLyNL** [comment] 2017-08-15 08:14
Can you please send the .jasp file to my a.ly@uva.nl

**Comment by AlexanderLyNL** [comment] 2017-08-16 13:54
Hi Nikita,

@TimKDJ found that the data leads to a matrix of all ones, we'll update the error message accordingly. Thanks for figuring this out for us. 

<img width="1320" alt="screen shot 2017-08-16 at 15 53 08" src="https://user-images.githubusercontent.com/10271675/29366738-223e5dc2-829b-11e7-8903-2aa557988ee5.png">

**Closed** 2017-08-22 09:44 UTC
Labels: Wait For Requester
