### ISSUE TITLE
Additional info ticked by default

### ISSUE THREAD

**Issue by JohnnyDoorn** [jasp-stats/jasp-desktop#1985] opened 2017-09-21 12:08 UTC
## Template for enhancement requests
 
* Enhancement: Make "additional info" ticked by default when plotting prior and posterior
* Purpose: Saving you one click at a time!

@EJWagenmakers what do you think?

**Comment by AlexanderLyNL** [comment] 2017-10-26 17:45
duplicate of issue #2083

**Closed** 2017-10-26 17:45 UTC
Labels: Duplicate, Type: Enhancement
