### ISSUE TITLE
B Crosstabs: Are the attached results correct?

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#297] opened 2015-02-15 14:02 UTC
Perhaps these results are correct, but I wouldn't have expected a table with the same counts in every cell to have a BF<sub>10</sub> greater than 1.

![screen shot 2015-02-15 at 3 00 05 pm](https://cloud.githubusercontent.com/assets/3240247/6203451/6f12fa88-b523-11e4-81df-3f6912fe7e0c.png)

**Comment by Tahiraj** [comment] 2015-02-16 16:06
@EJWagenmakers 
The result does not seem correct for Poisson sampling scheme. If we calculate for same counts where every cell frequency is equal to 1 for joint multinomial sampling or independent multinomial, BF10 is  less than zero.  The same is true even for small dimension of matrices.

![screenshot 2015-02-16 16 35 47](https://cloud.githubusercontent.com/assets/9108433/6214568/d5377074-b5f9-11e4-802b-ca5441c9eb62.png)

**Comment by EJWagenmakers** [comment] 2015-02-16 16:37
Yes, well, this appears to be a consequence of the Gunel & Dickey setup,
not a mistake in the software. We can figure this out after submitting the
paper. It is possible that a log-linear extension will deal with the issue.
Richard also noted a weird consequence of the Gunel & Dickey
representation. Another way is to study the solution from Jeffreys. At any
rate, it would be good to understand this behavior, but let's put it on the
to-do list.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by EJWagenmakers** [comment] 2015-02-20 09:38
This result is most likely not a bug, but a "feature" of the Gunel & Dickey setup. But I agree it is highly counter-intuitive. Luckily, nobody will run up against this. We should mention this issue in the help file though. So it's a 0.7 issue.

**Comment by jonathon-love** [comment] 2015-06-17 09:46
I can close this issue?

**Comment by Tahiraj** [comment] 2015-06-17 09:48
Yes you can close this issue.
Best
Tahira

**Closed** 2015-06-17 09:52 UTC
Labels: question
