### ISSUE TITLE
JASPEngine.exe stopped working

### ISSUE THREAD

**Issue by klladd** [jasp-stats/jasp-desktop#2405] opened 2018-03-08 22:49 UTC
Greetings -

New install of JASP 0.8.6 on a Optiplex 7040, i7-6700 @3.40, 64 bit, WIN Enterprise 10.0.16299 

Will open any given SPSS file, but upon attempting any analysis, the program crashes:

JASPEngine.exe stopped working

JASP has experienced an unexpected internal error.
""

Same crash on a second PC, also WIN 10 Enterprise.

Thoughts?

Thanks,

- Kevin

**Comment by FransMeerhoff** [comment] 2018-03-13 08:29
Hi @klladd 

Thanks for reporting this issue, but unfortunately we are not able to reproduce this error.
Could you give us some more information:
- Does this problem only arise when opening an SPSS file?
- Could you send an example SPSS file which make JASPEngine crash?

Kind regards
Frans Meerhoff

**Comment by klladd** [comment] 2018-03-13 10:34
Hi Frans –

The problem persists with any SPSS file. As a comparison, I’ve used files that are several years old as well as from the current version (24) available to me; I’ve attached one sample.

I haven’t attempted to use any other file type.

I was able to correct the issue by stepping back a version of JASP to 0851. That is working fine.

Thanks!


-          Kevin

**Comment by boutinb** [comment] 2018-03-13 11:09
We did not receive your file. But I doubt that it has to do with SPSS. Can you just try an example file, and run an analysis?
If this crash also, we will need more information. For this, I would like to ask you to run the JASPEngine directly. Therefore I send you a bat file (in a zip format): 
[runEngine.bat.zip](https://github.com/jasp-stats/jasp-desktop/files/1806598/runEngine.bat.zip)
If you unzip it, and copy this file to the installation of JASP 0.8.6 (Program Files\JASP 0.8.6.0). Double-click the runEngine.bat file (you would probably need admin right), the JASP Engine should start. If there are some errors, can you send us exactly which errors you see?

By the way, if you want to send us a file, send it in a ZIP format, and use directly the GitHub issues site to add a comment.

**Comment by boutinb** [comment] 2018-03-13 15:42
Sorry @klladd, but I cannot see the images you send. You have to do that directly in GitHub Issues, not from your email...

**Comment by klladd** [comment] 2018-03-13 15:59
![image](https://user-images.githubusercontent.com/37196191/37353488-d36178e6-26b5-11e8-9197-8e9251ea58f6.png)

![image](https://user-images.githubusercontent.com/37196191/37353498-d96fa4e2-26b5-11e8-86fd-43fd7a89a116.png)

![image](https://user-images.githubusercontent.com/37196191/37353510-def7c8f4-26b5-11e8-9467-b0057c589048.png)

**Comment by boutinb** [comment] 2018-03-13 16:04
Hi @klladd, I still cannot read the error messages in the images... Can you type it?

**Comment by FransMeerhoff** [comment] 2018-05-01 07:06
Hi @klladd 

I'm sorry that we can not proceed with this issue.
Do you have any new information from your side.
Or can we close this issue?

Kind regards 
Frans Meerhoff

**Comment by klladd** [comment] 2018-05-02 01:37
Hi Frans –

I had to move on to other projects and ran out of spare time to track down the JASP problem. Sorry I wasn’t much help from this end!


-          Kevin

**Comment by FransMeerhoff** [comment] 2018-05-02 06:58
Hi @klladd 

No problem of course.
I'll close this issue for now and you can reopen at any time if you want.
Our next release is planned very soon. The new version 0.9 might solve your problem.
Thanks for so far.

Cheers Frans Meerhoff

**Closed by FransMeerhoff** 2018-05-02 06:58 UTC
Labels: Wait For Requester
