### ISSUE TITLE
Bug: Moving mouse over variables automatically selects them

### ISSUE THREAD

**Issue by kiisudankan** [jasp-stats/jasp-desktop#2716] opened 2018-07-30 05:58 UTC
* JASP version: 0.9.01
* OS name and version: Windows 7
* Analysis: Any
* Steps to reproduce: Always happens

When attempting to choose the variables for any analysis, the variables are automatically selected when the mouse hovers over them even if no mouse button is pressed. This makes selecting variables virtually impossible. It happens on 0.8.5, 0.8.6 and 0.9.01. The problem is the same for mouse and trackpad. Only JASP has this issue for me. Help!

**Comment by FransMeerhoff** [comment] 2018-08-08 07:41
Hi @kiisudankan 

That's indeed very strange behaviour, but thanks for reporting this anyway.
You will not be wondered that we cannot reproduce this problem which makes it hard to
find the cause of such a problem, moreover because you say that this issue only happens with JASP.
Because you say that it happens on every analyses let's stick to one concrete case on 0.9.0.1
Could you check the following: From the  Data Library choose Descriptives and open the Sleep jasp example. If you click on the table in the results window  
- If you hover over ID does this directly goes to the Variables column?
- Does this happen also vice versa?
- If you hover over the checkbox 'Frequency tables' is it than activated too?
- If you open the Preference window, you can find it in the upper right button on the tabbar (with the hamburger button). Does this window has the same problems.

Thanks in advance
Frans Meerhoff

**Comment by kiisudankan** [comment] 2018-08-09 00:42
Hi Frans,

Thanks for looking into this. Its been driving me crazy for months.

However, for reasons that I cannot understand the problem has resolved. I checked the problem still occurred in an old data set (it did). Then I followed your instructions and opened the sleep example. The results of which were:

- If you hover over ID does this directly goes to the Variables column?
No.
- Does this happen also vice versa?
No
- If you hover over the checkbox 'Frequency tables' is it than activated too?
No
- If you open the Preference window, you can find it in the upper right button on the tabbar (with the hamburger button). Does this window has the same problems.
No
And in fact, the autoselecting problem also didn't happen either.

I then went back to the previous old data set, and found that the problem has also disappeared there too (and for another data set too). It seems that somehow opening the Data Library Sleep example has fixed the issue. I don't know how that would be possible.

Anyway, it works again, so I am happy...

Thanks!

**Comment by FransMeerhoff** [comment] 2018-08-09 09:08
HI @kiisudankan 

Strange, but good to hear that is works again.
I close the issue and you can reopen it if it occurs again.

Cheers
Frans

**Closed by FransMeerhoff** 2018-08-09 09:08 UTC
