### ISSUE TITLE
plots stopped working only with 0.9.1 (flatpak)

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-desktop#2881] opened 2018-10-26 14:28 UTC
* JASP version: 0.9.1 flatpak
* OS name and version: 4.14.78-1-MANJARO Linux
* Analysis: descriptive plots stopped working. worked in 0.9.0.1
* Steps to reproduce: open any dataset from the library or an own one; try to plot a boxplot etc produces the linked error message [https://gist.github.com/tomtomme/8147b739fd14213db0cfd6a7ff769aaf](https://gist.github.com/tomtomme/8147b739fd14213db0cfd6a7ff769aaf)

This might be a flatpak only issue. It  might be the same bug as this one [https://github.com/jasp-stats/jasp-desktop/issues/2854](https://github.com/jasp-stats/jasp-desktop/issues/2854)
However that bug started with 0.9.0.1, while for me with that version everything worked fine. My bug started with 0.9.1

**Comment by tomtomme** [comment] 2018-10-26 14:30
My

**Comment by JorisGoosen** [comment] 2018-11-02 16:16
Duplicate of #2854

**Closed by JorisGoosen** 2018-11-02 16:16 UTC
