### ISSUE TITLE
Non-parametric tests

### ISSUE THREAD

**Issue by christance** [jasp-stats/jasp-desktop#1038] opened 2015-10-31 23:43 UTC
I love your programme.  It works great as an alternative to SPSS.  However, it doesn't have options for non-parametric tests as yet.  Will that be coming soon?  Extremely looking forward to it.

**Comment by jonathon-love** [comment] 2015-11-01 12:03
absolutely! non-parametric t-tests will be in the next release. non-parametric ANOVAs are a little further off. non-parametric correlation is already in there of course.

cheers!

**Comment by philippberens** [comment] 2015-11-10 11:41
i second the request for non-parametric test - would be nice for teaching, because like this, what do you tell the students to do when they have non-normal data? also qq-plots for t-tests would be great.

**Comment by Indycool** [comment] 2016-06-01 08:36
I back this this request too, students asked me the same question: "what to do when a non-paramectric test is required?"

**Comment by diogenesbido** [comment] 2016-09-03 15:08
besides Wilcoxon, Mann-Whitney, Kruskal-Wallis, maybe some bootstrap or permutation methods

**Comment by andyroberts1234** [comment] 2017-06-22 20:00
Agree, bootstrapping and other non-parametrics would be great

**Comment by NoamTal** [comment] 2018-02-18 09:10
I was wondering if the non-parametric ANOVA tests (Friedman, Kruskal-Wallis) are still in plan. We teach the students in our institution how to conduct these tests using another software (IBM Statistica), but we plan to replace that software and teach them JASP instead (which we really admire and support), so that feature could be greatly helpful.

**Comment by shariellen** [comment] 2018-03-12 17:59
I would love to teach my research methods class with JASP, however, we have many small clinical data sets, and need nonparametric tests, especially Mann Whitney U and Wilcoxon signed ranks (we do a lot of pre/post design with small sets)
From my "to do" list with SPSS:
 Non-parametric tests - inferential
7.1.	Mann Whitney U for ranks
7.2.	Chi Square for nominal
7.3.	Wilcoxon signed ranks
7.4.	Friedman’s ANOVA
7.5.	Cochran’s Q
Correlational statistics
8.1.	Pearson product moment –    r
8.2.	Spearman rho – for rank data -    
8.3.	Cramer coefficient for nominal data
8.4.	Regression analysis for normal data with more than two variables
8.5.	Kendall’s W for ordinal data with more than two variables

**Comment by EJWagenmakers** [comment] 2018-03-12 20:27
@JohnnyDoorn knows the details, but we already have 7.1, 7.2, 7.3, 8.1, 8.2 for sure. Johnny, do we have more? Plus we are currently working to add a few that we don't have, such as the ones suggested by @NoamTal

**Comment by JohnnyDoorn** [comment] 2018-03-12 21:17
Hi,
I am currently implementing the Friedman/Kruskal-Wallis/Kendall's W tests - they will be in the next release! Since 7.5, 8.3, and 8.4 are all a bit different, they will be implemented later. 
The Bayesian version of the Wilcoxon/Mann-Whitney will also soon follow, fyi.
Cheers,
Johnny

**Comment by JohnnyDoorn** [comment] 2018-03-14 19:06
Hi Shariellen,
We are currently working on a JASP manual! However, I'm not sure when it will be finished - maybe @EJWagenmakers knows a little bit more ;)
Kind regards,
Johnny

**Closed** 2018-03-21 17:11 UTC
Labels: Layer: R, Priority 2: Medium, Type: Enhancement
