### ISSUE TITLE
Bonferroni-corrected post-hoc comparisons for interactions in classical ANOVA 

### ISSUE THREAD

**Issue by IndrajeetPatil** [jasp-stats/jasp-desktop#1300] opened 2016-04-24 13:41 UTC
Hi,

I am following up on a prior query: https://github.com/jasp-stats/jasp-desktop/issues/423#issuecomment-77344504.

I see that JASP now includes an option to have corrected post-hoc comparisons for *main effects*, but would it be possible to do such tests for *interaction* effects? Is there any plan to include this in future versions of JASP? This is one feature that is missing from SPSS and will be nice addition to the rich portfolio of JASP. 

Thanks,
Indrajeet

**Comment by raviselker** [comment] 2016-04-24 14:40
Duplicate of #423. I answered your question in #423.

**Closed by raviselker** 2016-04-24 14:40 UTC
