### ISSUE TITLE
Pairwise comparisons after RM ANOVA

### ISSUE THREAD

**Issue by lcoome** [jasp-stats/jasp-desktop#1596] opened 2017-01-24 00:17 UTC
Hi,
JASP uses the pooled error term from the ANOVA. SPSS does not. I thought that the prevailing view was that in RM designs it's better not to use the pooled error term. Could you please explain?
Thanks.

**Comment by JohnnyDoorn** [comment] 2017-01-26 12:57
Hi,
Thanks for pointing this out. JASP uses the afex package in R to compute RM ANOVA's - in the package manual it states that it uses the same approach as SPSS, so the results should be the same. Using the nonpooled error terms would indeed be the better option, as not doing so can have severe consequences for the type-1 error rates. 
Would you be so kind as to provide a data example where SPSS and JASP provide different results in this context? We can use this to investigate this difference, because it should not be the case that they offer different results.
Kind regards,
Johnny

**Comment by lcoome** [comment] 2017-01-26 20:22
<img width="627" alt="example" src="https://cloud.githubusercontent.com/assets/13381277/22348669/9b5f95be-e3da-11e6-8e61-f07b0515d11e.png">

These results are from a RM ANOVA with 4 measures from each of 151 participants.
It uses a pooled error term in the post hoc pairwise comparisons.
The pooled error term is calculated exactly as if it were a between-subjects design, as the SquareRoot(2*MSe/n), where n here is 151, but it’s the SAME 151 participants in the two conditions that are being compared.
Turkey’s test is designed for between-subjects only. The n represents the number of participants in the different conditions, but these are supposed to be independent observations (from different people).

And—to make matters worse, I’m pretty sure that the critical t you're using has 450 degrees of freedom, when it should have 150.

If you do actual paired t-tests between the different levels, the t's are all much different.

JASP should report the results from paired t-tests with the exact p, Bonferroni-corrected p, and Holm-corrected p.

I also don’t think that the Sheffé test is appropriate.

It appears as though you copied the code from the between-subjects ANOVA.

Is this helpful?

**Comment by JohnnyDoorn** [comment] 2017-02-03 11:11
Hi Lindsay,
Thanks again for your very elaborate answer! You are right about the pooled error terms and incorrectly defined p.values. I have gone through the R-code used in JASP and fixed the problem. It seemed like the cause was a package where we could not specify the error terms not to be pooled, which lead to similar treatment of the within subject variables as the between subject variables. The updated code (which will be in the next JASP release) now loops through the within subject variables and computes separate t-tests on them, then corrects the p-values with either Bonferroni or Holm. Again, thanks for taking your time and providing your example.
Kind regards,
Johnny

**Comment by lcoome** [comment] 2017-02-03 12:24
Thanks Johnny, glad to hear it helped.

**Comment by boutinb** [comment] 2017-03-15 10:44
This is solved in the new version 0.8.1

**Closed by boutinb** 2017-03-15 10:44 UTC
