### ISSUE TITLE
abbreviations compute columns are awkward

### ISSUE THREAD

**Issue by vandenman** [jasp-stats/jasp-desktop#2865] opened 2018-10-22 08:55 UTC
## Template for bug reports

* JASP version: 9.1
* OS name and version: windows
* Analysis: compute columns
* Steps to reproduce: 

1. create a new column with a name of only 3 letters.
2. try to create a new column based on the 3 letter column.
3. the name of the 3-letter column is ...

![image](https://user-images.githubusercontent.com/21319932/47284769-d657b000-d5e8-11e8-9881-2b8089bd7ffc.png)

this also goes for 4-letter columns. The two ... variables in the example are called `abc` and `abc2`.

## Template for enhancement requests
 
* Enhancement: don't abbreviate column names shorter than x.
* Purpose: readability.

**Comment by AlexanderLyNL** [comment] 2018-10-22 20:58
Duplicate of #2866

**Closed by AlexanderLyNL** 2018-10-22 20:58 UTC
