### ISSUE TITLE
QQ plot in repeated measures ANOVA

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1566] opened 2016-12-06 23:42 UTC
From the forum:
"Also, in the repeated measures ANOVA tab the Q-Q plot assumption is missing (but in the ANOVA tab it is there)."

**Comment by FransMeerhoff** [comment] 2016-12-08 08:09
@JohnnyDoorn 

Hi Johnny, Is there a special reason for this,
Or should we put this on the list ?

Gr. Frans

**Comment by boutinb** [comment] 2017-03-15 11:07
Duplicate of #848

**Closed by boutinb** 2017-03-15 11:07 UTC
Labels: Duplicate, Layer: R, Type: Enhancement
