### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2087] opened 2017-10-27 09:55 UTC
I'm teaching a course and a student could not install JASP. She got the folllowing error:

Runtime error!
Program: C:\Program Files\JASP 0.8.3.0\JASP.exe

A similar error was present under 0.8.3.1. I've asked her to make a GitHub issue. She indicated that this error was not uncommon (if you look online). Windows 10.

Cheers,
E.J.

**Comment by AlexanderLyNL** [comment] 2017-10-27 10:20
Duplicate of issue #2088

**Closed by AlexanderLyNL** 2017-10-27 10:20 UTC
Labels: Duplicate
