### ISSUE TITLE
Problem with graphics

### ISSUE THREAD

**Issue by Hello44** [jasp-stats/jasp-desktop#1161] opened 2016-02-12 14:21 UTC
I have a problem, I can't make graphics in t-test,
it's ok without graphics:
![jasp 1](https://cloud.githubusercontent.com/assets/17199204/13009266/d467c284-d19b-11e5-80f9-807620968878.png)
then i ask for graphic, i have an error:
![jasp 2](https://cloud.githubusercontent.com/assets/17199204/13009294/05ea7680-d19c-11e5-93b0-ad83cea1d016.png)
On my other computer it's ok, what can i do ?

Thank you ! ( and sorry for my bad english ! )

**Comment by boutinb** [comment] 2016-02-15 08:06
Hi,
I cannot reproduce this problem with the latest version of JASP (0.7.5 Beta 3). Which version do you use, and with which platform (Windows, Mac…)?

Kind regards,
Bruno

**Comment by Hello44** [comment] 2016-02-22 19:05
I work with Jasp(0.7.5 Beta 2), I have window 10.
The probleme is only in t-test, (in all t-test)  no problem with the other graphics. (in anova for example)
I don't understand.
Thank you !

**Comment by FransMeerhoff** [comment] 2016-02-23 11:08
Very soon JASP 0.7.5 will be released. Highly probable this week. This will surely solve this problem.

Kind regards

**Comment by boutinb** [comment] 2017-03-14 16:19
Do you have still this problem with the latest version (0.8,1)?

**Comment by boutinb** [comment] 2017-03-29 13:20
If this error still occurs, reopen this issue.

**Closed by boutinb** 2017-03-29 13:20 UTC
Labels: Type: Bug, Wait For Requester
