### ISSUE TITLE
packages missing error (linux)

### ISSUE THREAD

**Issue by dostodabsi** [jasp-stats/jasp-desktop#929] opened 2015-09-05 17:42 UTC
Hi Jonathon,

I'm on Linux Mint 17 (which counts as Ubuntu 14.04, right?) and use the latest JASP version from the ppa.  When running a Bayesian correlation, I get an error saying that the package "hypergeo" doesn't exist. When plotting some descriptives in anova or t-test (or whatever uses ggplot2), I get a missing "ggplot2" error.

Somewhat unrelated, I also get an "unused argument (probs = 0.01)" error when plotting prior and posterior in the t-test case.

cheers,
Fabian

![hypergeo_missing](https://cloud.githubusercontent.com/assets/6568110/9700485/1dd592ee-5405-11e5-83ad-9102e06eab47.png)

![ggplot2_missing](https://cloud.githubusercontent.com/assets/6568110/9700484/1bc0e7a6-5405-11e5-8953-cfc32274e81a.png)

![unused_arg](https://cloud.githubusercontent.com/assets/6568110/9700518/0b9f6a68-5406-11e5-9ad8-316ee749d690.png)

**Comment by jonathon-love** [comment] 2015-09-05 19:27
hey, thanks for your bug report. i'm guessing you're on ubuntu trusty? there's a problem with getting hypergeo on trusty, that i haven't been able to solve.
the ggplot2 issue i will have to look into too.

thanks for your report.

**Comment by dostodabsi** [comment] 2015-09-05 19:36
I'm actually on Linux Mint 17 -- which is similar to Ubuntu Trusty, but not the same. I guess this problem is different from a simple install? Because hypergeo installs just fine on its own.

The "unused arguments" bug seems quite general though, so maybe that should have priority (not many people use linux; although, of course, missing packages are a game breaker).

thanks for the quick reply!

**Comment by jonathon-love** [comment] 2015-09-05 19:49
> I guess this problem is different from a simple install? Because hypergeo installs just fine on its own.

yeah, there are two avenues for packages to be installed; one through R itself, and the other through the linux distros package manager. the only good mechanism for us to use is the package manager, which is problematic, because there are packages not available through the package manager, so i have to backport them to my PPA... but then these can have compatibility issues too! (which is what the problem with hypergeo is)

> The "unused arguments" bug seems quite general though

i think this is because of an older package on trusty, it's not a problem on vivid.

i've fixed the ggplot2 issue, there should be a new update available in the next half hour. the other issues will take me a bit longer to solve.

again, i really appreciate these reports.

**Comment by dostodabsi** [comment] 2015-09-05 19:57
ah, yeah, this sounds like a hassle. thanks for the super quick replies!

**Comment by jonathon-love** [comment] 2015-09-05 19:59
thankfully, it won't be an issue with linux distros from here on... only these older ones.

**Comment by dostodabsi** [comment] 2015-09-05 20:06
yeah, but I guess most people (and universities using linux) stick with LTS, and the next one will be April 2016 .. granted, though, this is only a tiny fraction

**Comment by jonathon-love** [comment] 2015-09-05 20:07
yeah, i'll get on top of it :)

**Comment by jonathon-love** [comment] 2015-09-05 20:30
hmm, i think i may have fixed the hypergeo issue as well.
if you run the ubuntu software updater, you should get the new version, and it should solve all but the last issue.

**Comment by dostodabsi** [comment] 2015-09-05 20:36
yes, excellent! both the hypergeo and ggplot2 issues are gone :)

**Comment by jonathon-love** [comment] 2015-09-05 20:38
hmm, at a guess, the last one is to do with us relying on a feature in R 3.1, which isn't available in 3.0

**Comment by jonathon-love** [comment] 2015-09-06 13:26
hey, i'm having difficulty reproducing the last issue you have. can you tell me if it still occurs with the latest version? (the version from last night)

**Comment by dostodabsi** [comment] 2015-09-06 13:36
yes

**Comment by jonathon-love** [comment] 2015-09-06 13:37
hmm, funny. it works on trusty, which *should* be the same as mint, but there's some difference. i'll try mint next.

**Comment by jonathon-love** [comment] 2015-09-06 15:31
what version of mint?! it's working fine for me (except, libqtsvg hasn't been installed, so all the icons are missing). 17.2 under cinnamon :/

**Comment by dostodabsi** [comment] 2015-09-06 16:36
17 Qiana

**Comment by jonathon-love** [comment] 2015-09-06 17:10
hmm, this last one is a tricky one. i can't reproduce it with qiana either. can you run JASP at the terminal (you can just type `JASP`) and send the output?
you should get a bunch of warnings about R packages not being the expected versions.

with thanks

**Comment by jonathon-love** [comment] 2015-09-06 17:13
oh, wait, you'll need to open a dataset before all the R package info will be produced.

**Comment by dostodabsi** [comment] 2015-09-06 17:14
I sent you the file logging the whole process.

**Comment by jonathon-love** [comment] 2015-09-06 19:25
this is totally weird. your output reports that you're using rjsonio-0.98, but you've updated to 1.3 !
have you got the new JASP version today? (from the software updater), if that doesn't fix it, them i'm pretty beat :(

**Comment by dostodabsi** [comment] 2015-09-06 19:32
I think we are on the wrong thread; classical log odds ratio work now (the json problem, see other thread); the t-test problem (unused argument) is still there, however.

**Comment by jonathon-love** [comment] 2015-09-06 19:37
ok! awesome!

**Comment by jonathon-love** [comment] 2015-09-06 19:44
OK, the two remaining issues come down to the same problem, so i'm going to close this thread, and move to the other one.

**Closed by jonathon-love** 2015-09-06 19:44 UTC
Labels: bug
