### ISSUE TITLE
Mouseover is misaligned in JASP 0.9 SEM module

### ISSUE THREAD

**Issue by HeikoBreitsohl** [jasp-stats/jasp-desktop#2644] opened 2018-06-21 10:04 UTC
Hi JASP Team,
in the latest version of the SEM module, the menu elements seem not to react (i.e. become highlighted) when the _tip_ of the mouse arrow is over them, but when roughly the _center_ is. This is a bit inconvenient, as you have to force yourself to purposely point at the "wrong" element.
For instance, under Statistics->Error Calculation, you have to point at "Standard" to highlight "Robust", and you have to point _above_ "Standard" to highlight it.

* JASP version: 0.9
* OS name and version: Windows 10
* Analysis: SEM
* Steps to reproduce: mouse over any button or menu

**Comment by vankesteren** [comment] 2018-06-22 09:38
I cannot reproduce this unfortunately. Are there any particular settings that I should be aware of? For example, do you have display scaling turned on, or have you installed a custom mouse cursor?

My experience on windows 10, fresh install of JASP:

![sem_module](https://user-images.githubusercontent.com/11596858/41769776-b18df5dc-7610-11e8-8ece-9cc74a596c44.gif)

**Comment by akashrajkn** [comment] 2018-06-22 10:07
@vankesteren could this be a highDPI issue?

**Comment by vankesteren** [comment] 2018-06-22 12:37
Let's see what @HeikoBreitsohl answers :)

**Comment by HeikoBreitsohl** [comment] 2018-06-25 07:48
Thanks for helping out!
It appears this is an issue specific to my wireless mouse (Rapoo model 1010). Still, I am pretty sure it occurred only after updating to JASP 0.9.

**Comment by vankesteren** [comment] 2018-06-25 11:20
Probably a driver issue then? I'm closing this. Feel free to reopen if you consider this unsolved.

**Closed by vankesteren** 2018-06-25 11:20 UTC
