### ISSUE TITLE
Problems with “Descriptive plots” and Bayesian Independent Samples T-Test

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [jasp-stats/jasp-desktop#1242] opened 2016-03-15 17:51 UTC
[T-testPlot.docx](https://github.com/jasp-stats/jasp-desktop/files/174496/T-testPlot.docx)

**Comment by FransMeerhoff** [comment] 2016-03-16 10:18
Dear NikitaKhromov,

Can you help us with the following:
- Send us the data file you are using (CSV or other type)
- Specify the platform you are running JASP

Kind regards
Frans Meerhoff

On 15 Mar 2016, at 18:51, NikitaKhromov-Borisov <notifications@github.com<mailto:notifications@github.com>> wrote:


T-testPlot.docx<https://github.com/jasp-stats/jasp-desktop/files/174496/T-testPlot.docx>

**Comment by NikitaKhromov-Borisov** [comment] 2016-03-16 10:25
Dear Frans,
thank you for the instant response.
Here I have attached two examples.
My OS is Win7

Best regards,

Dr. Nikita Khromov-Borisov
Senior Research Fellow
Vreden Russian Research Institute of Traumatology and Orthopedics
Acad. Baykov Str, 8
Saint Petersburg
195427
RUSSIA

http://independent.academia.edu/NikitaKhromovBorisov



2016-03-16 13:18 GMT+03:00 FransMeerhoff <notifications@github.com>:

> Dear NikitaKhromov,
>
> Can you help us with the following:
> - Send us the data file you are using (CSV or other type)
> - Specify the platform you are running JASP
>
> Kind regards
> Frans Meerhoff
>
> On 15 Mar 2016, at 18:51, NikitaKhromov-Borisov <notifications@github.com

**Comment by boutinb** [comment] 2016-03-16 11:46
Dear Nikita,
I think you forgot to send the 2 attachments. I cannot see them.

Best regards,
Frans,

**Comment by NikitaKhromov-Borisov** [comment] 2016-03-16 13:02
OK, here I repeat them in packed and unpacked forms. However, it's very
strange: I see them as attachemnets to my message I have sent you.
Moreover, I attached them yeasterday to my message at GibHub.
Best,
Nikita

2016-03-16 14:46 GMT+03:00 bruno boutin <notifications@github.com>:

**Comment by FransMeerhoff** [comment] 2016-03-16 14:13
Dear Nikita,

Sorry to bother you again but I still do not have the data files.

Can you send me once more the attachments directly to the CC mail adres?
Attachments to github mail addresses will not arrive.

I do can see the Word documents you’ve added to the issues.
Unfortunately it is impossible to solve the issue without having the data file.

Kind regards
Frans Meerhoff


On 16 Mar 2016, at 14:02, NikitaKhromov-Borisov <notifications@github.com<mailto:notifications@github.com>> wrote:

OK, here I repeat them in packed and unpacked forms. However, it's very
strange: I see them as attachemnets to my message I have sent you.
Moreover, I attached them yeasterday to my message at GibHub.
Best,
Nikita

2016-03-16 14:46 GMT+03:00 bruno boutin <notifications@github.com<mailto:notifications@github.com>>:

**Comment by NikitaKhromov-Borisov** [comment] 2016-03-16 15:50
Dear Frans,
sorry, I don't know what is CC mail address?
But I can copy and open one of my .doc file here:
[image: Встроенное изображение 1]

and here
[image: Встроенное изображение 2]

and here:
https://github.com/jasp-stats/jasp-desktop/files/174496/T-testPlot.docx

Anyway, the first problem:

I try to analyse a 2x2 table:

a

x

1

a

y

5000

b

x

10

b

y

5000



However, in the output

*Contingency Tables*

*Contingency Tables *

*x *

*a *

*x *

*y *

*Total *

a

0.00

5000

5000

b

10.00

5000

5010

Total

10.00

10000

10010

You see, the initial value 1 in the a,x cell becomes 0

The second problem:

When I tried to carry out t-test with another data set. Unfortunately, when
I checked the option “Descriptive plots” the following report appears:

[image: Встроенное изображение 3]


When I tried to carry out the Bayesian Independent Samples T-test the
program stalled with the following report:

[image: Встроенное изображение 4]


Thank you for advance.
cheers,
Nikikta

2016-03-16 17:13 GMT+03:00 FransMeerhoff <notifications@github.com>:

> Dear Nikita,
>
> Sorry to bother you again but I still do not have the data files.
>
> Can you send me once more the attachments directly to the CC mail adres?
> Attachments to github mail addresses will not arrive.
>
> I do can see the Word documents you’ve added to the issues.
> Unfortunately it is impossible to solve the issue without having the data
> file.
>
> Kind regards
> Frans Meerhoff
>
>
> On 16 Mar 2016, at 14:02, NikitaKhromov-Borisov <notifications@github.com

**Comment by boutinb** [comment] 2016-03-17 16:29
Dear Nikita,
Please sent an email directly to F.A.M.Meerhoff@uva.nl<mailto:F.A.M.Meerhoff@uva.nl>, with as attachment 2 files: the data of your experiment, and your .jasp file. If it does not accept it, just zip these 2 files, and this zip file as attachment.

Kind regards,
Frans

**Comment by raviselker** [comment] 2016-03-18 10:31
Just a general comment: when replying to issues directly by email, your issue comment (on github) will include your email signature and all the previous comments to an issue (unless you deleted these in your reply). This makes the github issue very unreadable. It's better to respond to issues directly on the github website.

**Comment by FransMeerhoff** [comment] 2016-03-22 14:51
Dear Nikita,

Your original problem:Problems with “Descriptive plots” and Bayesian Independent Samples T-Test #1242; we can't reproduce this problem.

I've tested it on 
- Windows 7 32-bit machine.
- JASP version 0.7.5,5
- Tme.csv data file you've sent us.

One tiny 'strange' thing we noticed is that in your error message '.... c:/Users//AppData...' the username is empty.

Our only advise at the moment is (if possible) :
- Remove previous installation(s) of JASP
- Reinstall JASP 0.7.5.5 and test again (and be alert that installation han no problems)

![screen shot 2016-03-22 at 15 33 09](https://cloud.githubusercontent.com/assets/15656960/13955160/f2d24aac-f043-11e5-8af6-1ad99c4044ce.png)

Kind regards 
Frans Meerhoff

**Comment by NikitaKhromov-Borisov** [comment] 2016-03-22 15:19
Dear Frans,
sorry. I foud that it is a problem with my computer. On the other computer
all is OK.
Situation is strange: nstallation has no problem. But osme options lead to
that errors.

Best regards,
Nikita

2016-03-22 17:51 GMT+03:00 FransMeerhoff <notifications@github.com>:

**Comment by FransMeerhoff** [comment] 2016-03-22 15:29
Dear Nikita,

No problem. If the problem arise again, we create a new issue.
I'll close this one.

Regards, Frans

**Closed by FransMeerhoff** 2016-03-22 15:29 UTC
Labels: bug
