### ISSUE TITLE
Table renderer does not honour individual table status

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#784] opened 2015-07-10 23:31 UTC
Not vital for the beta release. For Bayesian contingency tables, ticking some options redoes the calculations (needlessly). For instance, this holds for "additional info" after "plots" has been selected; it holds for "posterior plot", and it holds for "log odds ratio" . 
![image](https://cloud.githubusercontent.com/assets/8603015/8630896/f7ba1b04-2720-11e5-8635-bbb854f02197.png)

**Comment by jonathon-love** [comment] 2015-07-11 00:24
i don't actually think it re-does analyses. i think the issue is with the table renderer putting the loading indicator, even when the values aren't actually being recalculated.

@dropmann, could you take a look at this?

each table can have a status which can be set to "complete". when "complete" it shouldn't show the loading indicator. if no status is specified, then it inherits from the overall analysis. i think you're inheriting from the overall analysis, and ignoring the status on the individual tables.

**Comment by dropmann** [comment] 2015-07-13 13:44
I've committed a fix and check as well as i could but it would be worth @jonathon-love testing it in case i've miss understood something.

**Closed** 2015-07-13 13:48 UTC

**Comment by jonathon-love** [comment] 2015-07-13 13:55
yup, seems to work. though there appears to be a related issue with #798
