### ISSUE TITLE
Runtime Error - JASP crashes

### ISSUE THREAD

**Issue by MayaEn** [jasp-stats/jasp-desktop#1816] opened 2017-06-14 18:01 UTC
## Environment (for bugs)

* JASP versions: 0.8.1.2-64-bit, 0.8.1.1-64-bit, 0.8.1.2
* OS name and version: Windows 8.1 64-bit
* Analysis: Sometimes happens when immediately opening file, sometime when requesting analysis, sometimes when scrolling down the list of variables to add a variable to an analysis. Happens with sav and csv files, as well as with the example files.
Hi,
This is the error I get:
![runtime_error](https://user-images.githubusercontent.com/29002442/27144906-45e67114-513c-11e7-929a-be337ff5c011.png)
And then JASP crashes. I tried installing different JASP versions and it did not help.
Thanks!

**Comment by boutinb** [comment] 2017-06-19 08:08
@MayaEn This is really strange... We have plenty of Windows users that run JASP without problem... Did you try to install the ZIP version (http://static.jasp-stats.org/JASP-0.8.1.2-64-bit.zip)?

**Comment by MayaEn** [comment] 2017-06-21 16:52
Yes, and it crashes as well.

**Comment by boutinb** [comment] 2017-06-27 09:05
@MayaEn Does this crash happen on another laptop/PC? This crash might be caused by too little memory available... What are the characteristics of your PC?

**Comment by MayaEn** [comment] 2017-06-27 21:33
Oh, I did not think about that. Yes, it only happened to me on my laptop.
Processor: i7
RAM: 4 GB
What other properties are relevant?

**Comment by boutinb** [comment] 2017-07-03 08:05
@MayaEn It's quite difficult to guess what goes wrong on your Laptop... A wild guess is that JASP does not get enough memory to run. Do you have many applications running? Did you try to reboot your laptop?

**Comment by boutinb** [comment] 2017-12-19 10:58
@MayaEn Does this problem still occur?

**Comment by AlexanderLyNL** [comment] 2018-10-11 18:52
This problem should be fixed with our new builds:

https://jasp-stats.org/download/

Please open a new issue if the problem reappears.

**Closed by AlexanderLyNL** 2018-10-11 18:52 UTC
Labels: Wait For Requester
