### ISSUE TITLE
incompatible with window 8?

### ISSUE THREAD

**Issue by yinyint** [jasp-stats/jasp-desktop#172] opened 2015-01-15 03:48 UTC
My operating system is Window 8. I tried to use my own csv file as well as the default files to run it. Either way, JASP.05 STOPPED working right after my first descriptive analysis. It showed the message that "This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information". This message was from Microsoft Visual C++ Runtime Library which I do not know what it is for and never use it.

Then, it showed the message from JASP.EXE that "A problem casued the program to stop working correctly. Windows will close the program and notify you if a solution is available."

Well, I plan to demonstrate my classmates how to run JASP in tomorrow's class.

**Comment by jonathon-love** [comment] 2015-01-15 08:11
hi, thanks for your report

we build and test JASP on windows 8, so it isn't a compatibility issue with the whole OS. this is something more specific i think.

you wouldn't happen to have RStudio, or R, or Rcpp, or RInside installed? These things *shouldn't* cause problems for JASP, but there may be a conflict we haven't anticipated.

> Either way, JASP.05 STOPPED working right after my first descriptive analysis

can you clarify, did it produce a results table *and then* stop working, or did it stop *before* producing results?

Also, can you give me some details on your OS. it's windows 8 (not 8.1 ?), 32-bit or 64-bit? and are you using the 32-bit or 64-bit version of JASP?

with thanks

**Comment by yinyint** [comment] 2015-01-15 13:10
Thank you for the quick reply. 

It did produce the first result table; however when I tried to add one more variable it then stopped working. I didn't even have chance to try a t test. 
I do have Rstudio installed. I installed 64 bit version of JASP. My computer is 8.1 enterprise, 64 bit.

We are going to do a JASP usability test in class. What kind of questions you would like to know from our usability test? I am Dr. mueller's student. We had a lunch together with  Shane and my lab mates in long beach SCiP conference.

Thank you,
Sarah

Yin Yin ( Sarah) Tan

**Comment by jonathon-love** [comment] 2015-01-15 16:17
oh, hey, sarah, i remember you now!

my suspicion is that the R that JASP uses, is finding the libraries from your RStudio install, using those, and because they're compiled with differently, it crashes.

i've added a thing that will hopefully prevent this, try this version:

https://static.jasp-stats.org/JASP-0.5.1-64bit-Setup.exe

if that version still doesn't work, you could try uninstalling RStudio and R, and see if that fixes it (only as a temporary measure! ... just to see if that fixes the issue)

oh wow, it will be great to have some useability feedback. ooh, we've changed a couple of things recently that impact usability directly. ooh, how long have i got? i might try and make you a version with some of our recent changes.

**Comment by jonathon-love** [comment] 2015-01-15 19:59
so one question we have at the moment is to do with graph resizing.

when the user resizes a graph should it retain the text-size, or should the text-size scale up with the rest of the image? Excel, SPSS, LibreOffice Calc, R, all keep the text-size the same, but some members of our team feel very strongly that the text should scale as well.

i appreciate this is possibly the sort of question that falls outside the sort of useability study you were planning, but i just thought i'd mention it.

**Comment by yinyint** [comment] 2015-01-15 20:54
Hi Jonathon,

I think I have figured out where the problem is. I installed the new
version in your previous email and it can run pretty nice. However, there
is still one bug. When I had a longer list of variables, I would scroll
down the "variables" bar in order to select one to use. At that time the
error message showed up and then JASP stopped working and disappeared. If I
do not scroll down the list, everything is perfectly fine.

We are done with our class for today. Everyone likes JASP! We are happy to
have this free, open software to use and visualize the results in the table
form right away. That is nice that we don't need to create the table by
ourselves.

However, we didn't see any plot on the 0.5 version. If you can give me your
new version (includes plot function), we are very happy to add the question
(i.e., resize the text). This is Shane's Stats 2 class. He is out of town
today so I was his temporary TA. We will work on this project for two weeks
I think. Everyone will evaluate JASP using their own data set.

Thank you,
Sarah

On Thu, Jan 15, 2015 at 11:17 AM, Jonathon Love <notifications@github.com>
wrote:

> oh, hey, sarah, i remember you now!
>
> my suspicion is that the R that JASP uses, is finding the libraries from
> your RStudio install, using those, and because they're compiled with
> differently, it crashes.
>
> i've added a thing that will hopefully prevent this, try this version:
>
> https://static.jasp-stats.org/JASP-0.5.1-64bit-Setup.exe
>
> if that version still doesn't work, you could try uninstalling RStudio and
> R, and see if that fixes it (only as a temporary measure! ... just to see
> if that fixes the issue)
>
> oh wow, it will be great to have some useability feedback. ooh, we've
> changed a couple of things recently that impact usability directly. ooh,
> how long have i got? i might try and make you a version with some of our
> recent changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jasp-stats/jasp-desktop/issues/172#issuecomment-70111211>
> .
>



-- 
Yin Yin (Sarah) Tan

**Comment by jonathon-love** [comment] 2015-01-15 21:07
hi yin yin,
i'm glad everyone likes it!

can i just clarify a few points?

> I installed the new version in your previous email and it can run pretty nice.

so the new version fixed the problem that you were having? the old version wouldn't work, but the new one would?

> However, there is still one bug. When I had a longer list of variables, I would scroll down the "variables" bar in order to select one to use. At that time the error message showed up and then JASP stopped working and disappeared. If I do not scroll down the list, everything is perfectly fine.

are you able to send me the dataset that caused this problem? my email is jon [at] thon [dot] cc

i'll see what i can do about providing a version with plotting.

thanks **so** much for your work yin yin, this sort of testing is really valuable! how much longer will the students be using JASP?

with thanks

jonathon

**Comment by yinyint** [comment] 2015-01-15 21:32
Hi Jonathon,

I used the prebuilt data set "political democracy" which also caused this
problem. My computer is Window 8.1 64bit. I didn't try to uninstall Rstudio.

I think that the students will continue to evaluate the program for a
couple of weeks. But I think everyone of us will use JASP whenever possible.


On Thu, Jan 15, 2015 at 4:07 PM, Jonathon Love <notifications@github.com>
wrote:

> hi yin yin,
> i'm glad everyone likes it!
>
> can i just clarify a few points?
>
> I installed the new version in your previous email and it can run pretty
> nice.
>
> so the new version fixed the problem that you were having? the old version
> wouldn't work, but the new one would?
>
> However, there is still one bug. When I had a longer list of variables, I
> would scroll down the "variables" bar in order to select one to use. At
> that time the error message showed up and then JASP stopped working and
> disappeared. If I do not scroll down the list, everything is perfectly fine.
>
> are you able to send me the dataset that caused this problem? my email is
> jon [at] thon [dot] cc
>
> i'll see what i can do about providing a version with plotting.
>
> thanks *so* much for your work yin yin, this sort of testing is really
> valuable! how much longer will the students be using JASP?
>
> with thanks
>
> jonathon
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jasp-stats/jasp-desktop/issues/172#issuecomment-70161732>
> .
>



-- 
Yin Yin (Sarah) Tan

**Comment by jonathon-love** [comment] 2015-01-16 16:04
ah, yup, the issue is that one of the columns has no title. i have put a fix in our development branch, and it will be in the next release.

thanks for the report!

**Closed by jonathon-love** 2015-01-16 16:04 UTC
