### ISSUE TITLE
"Unable to Save File, File in Use" error

### ISSUE THREAD

**Issue by AndrewDWilson** [jasp-stats/jasp-desktop#2266] opened 2018-01-13 15:48 UTC
I have run a bunch of analyses in v0.8.4. If I open a previously created .jasp file and edit anything, I am unable to save it; I get a "File XXXX is being used by another application" error. 

I just downloaded 0.8.5.1 and I'm getting the same error, and I have for several versions. 

I'm running this on Windows 10 64bit. 

Example JASP file and screenshot attached.
-andrew
[File In Use Error.zip](https://github.com/jasp-stats/jasp-desktop/files/1628479/File.In.Use.Error.zip)

**Comment by EJWagenmakers** [comment] 2018-01-14 21:03
Also just mentioned on Twitter: "Does anyone else get an 'unable to save file; open in another application' in @JASPStats when you open, edit and then try to resave a .jasp file? It's killing me"

**Comment by FransMeerhoff** [comment] 2018-01-16 09:38
Hi @AndrewDWilson 

Thanks for reporting us, unfortunately we do not have a repro path for this.
If you are able to reproduce it could you try the following:

On Windows there exists a 'Resource Monitor'. With this application it is possible to check which application uses which file handles.  You can start it by typing 'resmon' in the Windows Search field and run it from there (preferred as administrator).
In this application there is the tab 'Associated Handles' . If you type here the file name you want to save, it shows all the applications that have open handles to this file, and you could also end that process if you want from there.

I hope that this give us the cause of this problem.

Kind regards
Frans Meerhoff



https://docs.microsoft.com/en-gb/sysinternals/downloads/process-explorer

**Comment by FransMeerhoff** [comment] 2018-01-16 09:41
Hi @AndrewDWilson 

PS 
The link on the bottom of the previous comment is another tool that give similar information about open file handles but with extra info.

**Comment by AndrewDWilson** [comment] 2018-01-16 13:24
OK, some results; see attached image

I snapped this after I had double clicked on the file, edited the title and gone to save. I generated the error. I then searched for the file in the Resource Manager; as you can see, 4 instances of JASPEngine.exe seem to have it.

![resourcemonitor](https://user-images.githubusercontent.com/32539835/34990945-cff1ef6e-fabf-11e7-8e94-df8e652e8bf9.JPG)

I then looked at the processes reported in the Manager. The Resource Manager reports JASP.exe and 4*JASPEngine.exe (see the other attached). They all go away when I close JASP, and all come back when I reopen it. No idea if that's normal :)

![allthejasps](https://user-images.githubusercontent.com/32539835/34991147-6eb705bc-fac0-11e7-8011-54ae5f968ee6.JPG)

Thanks
-andrew

**Comment by FransMeerhoff** [comment] 2018-01-16 15:53
Hi @AndrewDWilson 

Thanks a lot for the info. I do have a reproduction path now.
The 4 JASPEngine.exe processes that you see are in principal normal. (We start 4  engine processes for to perform the analyses because of parallel processing, and so for performance). But is is not normal of course that it locks the original read file. We have definitely a clue now to solve this issue.
A work-around on my Windows computer was to start JASP first, then open the file from JASP,  and not with a double click. 
We hope to solve this in the next version. but I will let you know.

Kind regards
Frans Meerhoff

**Comment by AndrewDWilson** [comment] 2018-01-17 14:19
Thanks! At least you have a foot in the door, and thanks for the workarounds

**Comment by boutinb** [comment] 2018-02-06 09:24
This will be fixed in 0.8.6

**Closed by boutinb** 2018-02-06 09:24 UTC
Labels: OS Windows, Type: Bug

**Comment by Saguaroman** [comment] 2018-06-07 18:59
I'm running JASP 0.8.6 and getting the same error (see screenshot) across two computers and two different JASP files).  The resource monitor indicates that only JASP.exe is accessing the file (see screenshot) but it still gives the error that the file is being used by another application.  Any ideas?  Thanks!

![screenshots](https://user-images.githubusercontent.com/40039345/41120063-4cad586a-6a49-11e8-828e-8dbd69673359.jpg)

**Comment by Saguaroman** [comment] 2018-06-08 14:56
One workaround that seems to sometimes work is to "save as" a different file name... it can do that, but it can't just "save."  And then it seems to work fine on the newly saved files...

**Comment by Saguaroman** [comment] 2018-06-08 15:40
The "save as" workaround is particularly effective when some output has been generated. The real problem files seem to be ones I was working on without any associated output. Somehow generating output along with the .jasp file seems to make all the saving problems go away.

**Comment by AlexanderLyNL** [comment] 2018-06-09 13:55
Dear @Saguaroman,

Thanks for this insight. Could you please provide us a data file and exact instructions to produce a jasp file that gets corrupted? This will us insights to which process blocks the writing to the file. 

Cheers,
Alexander

**Comment by Saguaroman** [comment] 2018-06-09 15:02
Thanks.
Here's the sequence -- I've done this a few times with various files and it consistently produces the error.  

-Create a data file in excel, save in .csv.  (see link below for "sample.csv" file on which I just did this)
-Open that csv file in JASP (file-open)
-Save and exit JASP.
-Reopen JASP, open the sample.jasp file (file-open) (see below for link to this file)
-Make a change to the file (e.g., I changed the "T1" variable to continuous instead of categorical)
-Try to save file (File-save)
-Get error "File [file path and name] is being used by another application".
-As noted, if I instead use "save as" and save it under a different file name, things then seem to progress without any problem. So I've figured a workaround, but it's a weird glitch!

Here's the .csv file link:  https://drive.google.com/file/d/1CbGoaeUXPunhb1fm34Vi8dU5Ix1SV3D6/view?usp=sharing 
Here's the .jasp file that (for me) won't save after a change: https://drive.google.com/file/d/1cO9RCf_nPOAsLF1k_JmwNRIwYkb_BX1e/view?usp=sharing

Thanks!
