### ISSUE TITLE
post hoc for interaction

### ISSUE THREAD

**Issue by jquadril** [jasp-stats/jasp-desktop#1298] opened 2016-04-21 16:24 UTC
Any chance you can add post-hoc capabilities for interaction effects on ANOVA

**Comment by raviselker** [comment] 2016-04-22 11:02
Duplicate of #423. We definitely want to implement this, but the implementation unfortunately is not as straightforward as it appears.

**Closed by raviselker** 2016-04-22 11:02 UTC

**Comment by R180** [comment] 2018-05-01 14:43
Did this ever get addressed in JASP? It does seem to exist in R, and in some other open-access R-based stats programs.
