### ISSUE TITLE
ANOVA: error

### ISSUE THREAD

**Issue by Franzilatanzi** [jasp-stats/jasp-desktop#1340] opened 2016-06-02 08:14 UTC
Hello,

I tried to calculate a repeated-measures ANOVA but as soon as I define a between-subject factor an error message appears. The same happens for a regular univariate ANOVA. What's wrong?

**Comment by raviselker** [comment] 2016-06-06 14:12
Do you get the same error as described in issue #1320?

**Comment by cameissner** [comment] 2016-06-17 16:45
I get the same error as #1320...

**Comment by boutinb** [comment] 2017-03-20 11:48
Duplicate of #1320

**Closed by boutinb** 2017-03-20 11:48 UTC
Labels: Duplicate
