### ISSUE TITLE
Nothing appears in output/results window

### ISSUE THREAD

**Issue by patwms** [jasp-stats/jasp-desktop#1387] opened 2016-07-26 20:23 UTC
I've installed JASP 0.7.5.6 on a PC running Windows 7. I can load data files but opening any of the analysis tabs and selecting variables has no effect on the results/output window. It never changes from the Welcome to JASP! opening message.

A similar inquiry from another user in this forum (JASP install issue for Windows) was posted last January and responses indicating that the issue was being looked into, but no solution has been offered.

Could there be other programs on the PC that are interfering? If so, what might the culprits be? Or is some support program required that could be missing on the PC?

**Comment by FransMeerhoff** [comment] 2016-07-26 21:18
Hi @patwms 

1. We indeed had a similar problem before.
This problem was caused by a system that had an extra nvidia video card installed.
Can you check if you use the same video card, or if another extra video card is installed?

2. We offer the possibility to download a zipped installed version of Jasp. This means that you can download that zip file, and try to run JASP from this unzipped folder. This might be a work around for your problem. 
The 32 bit version can be found at: http://static.jasp-stats.org/JASP-0.7.5.6-32-bit.zip
The 64 bit version can be found at: http://static.jasp-stats.org/JASP-0.7.5.6-64-bit.zip

Regards
Frans Meerhoff

**Comment by patwms** [comment] 2016-07-27 14:00
Thanks Frans. I'll give those things a try.

**Comment by boutinb** [comment] 2017-03-20 12:05
Do you have still this problem?

**Comment by patwms** [comment] 2017-03-20 16:15
Thanks for asking. All seems to be OK now.

**Comment by AlexanderLyNL** [comment] 2017-03-20 16:42
Great I'm closing this issue then.

**Closed by AlexanderLyNL** 2017-03-20 16:42 UTC
Labels: Layer: Core, Wait For Requester
