### ISSUE TITLE
Unable to save/load jasp files (on Ubuntu)

### ISSUE THREAD

**Issue by JohnnyDoorn** [jasp-stats/jasp-desktop#2401] opened 2018-03-07 14:55 UTC
* JASP version: 8.6
* OS name and version: Ubuntu 16.04
* Analysis: 
* Steps to reproduce: try to save a file as jasp file, then try to open it again.

First off, when I click 'save as', and I click (for instance) my 'Documents' folder, it does not open this folder, but my '/' folder.
Secondly, when I save it, I have to add .jasp manually (but this is not abnormal on ubuntu). When I then try to open the file, it gives the following error (either with or without adding the .jasp extension to the filename):
"Unable to open file.
Real out of signed integer range"
See attached screenshot and jaspfile, maybe you are able to open it
[failedSaveLoad.zip](https://github.com/jasp-stats/jasp-desktop/files/1789554/failedSaveLoad.zip)
.
![saveissuejasp](https://user-images.githubusercontent.com/15704203/37099112-e4ef2800-221f-11e8-96cc-ca210d75e24a.png)

**Comment by AlexanderLyNL** [comment] 2018-03-07 15:03
Does this work for you?

https://github.com/jasp-stats/jasp-desktop/issues/2386#issuecomment-371142731

If so, then close this, because this is then a duplicate of issue #2386

**Comment by JorisGoosen** [comment] 2018-03-08 10:36
It wasnt a duplicate, it had something to do with very large timestamps, this is fixed now and will be pushed soon.

**Closed by JorisGoosen** 2018-03-08 10:36 UTC

**Comment by JorisGoosen** [comment] 2018-03-08 14:20
Can you check it by running flatpak update && flatpak run org.jasp.JASP?
It should work now

**Comment by JohnnyDoorn** [comment] 2018-03-08 15:03
Yes! I can save/load. I do have to manually add the .jasp extension though, but I guess that's a different issue.
