### ISSUE TITLE
Annotations vanished upon reopening file

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1321] opened 2016-05-16 23:26 UTC
I just had this unfortunate experience that I am now trying to recreate. First, I wrote a lot of annotations at the beginning of a JASP file. Then I saved the file, closed it, and reopened it. The annotations were gone. So here is a file with annotations, properly saved:
![image](https://cloud.githubusercontent.com/assets/8603015/15306824/3a3ace4a-1bce-11e6-9f75-061780cd1307.png)

Now I'm closing the file, and reopening it:
![image](https://cloud.githubusercontent.com/assets/8603015/15306841/5f8d05c8-1bce-11e6-8cbc-39da0bcb4378.png)

Gone are all my annotations! This should not be happening. Am I missing something?

**Comment by EJWagenmakers** [comment] 2016-05-16 23:42
So when I rename the .jasp file to a .zip and inspect the .html file, it *does* show the comments! So they have not vanished, but they are not displayed properly. But perhaps I misunderstand something...

**Comment by akashrajkn** [comment] 2016-05-17 01:18
@EJWagenmakers , I am not able to reproduce this issue. Can you email the .jasp file ?

**Comment by boutinb** [comment] 2017-03-20 09:36
@EJWagenmakers I cannot either reproduce this problem. Do you?

**Comment by EJWagenmakers** [comment] 2017-03-20 12:59
It may have been fixed in a later release. If this resurfaces I will let you know.
E.J.

**Comment by AlexanderLyNL** [comment] 2017-03-20 16:58
Good I consider this solved and close this issue.

**Closed by AlexanderLyNL** 2017-03-20 16:58 UTC
Labels: Wait For Requester
