### ISSUE TITLE
State system in Bayesian t-test

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#749] opened 2015-06-23 09:14 UTC
In the Bayesian t-test, ticking and unticking the box "additional info" means that the entire computation and plotting exercise is done anew. This is not required; ideally, ticking and unticking the box "additional info" simply makes the additional information appear or vanish immediately, without a recompute.
![image](https://cloud.githubusercontent.com/assets/8603015/8302731/01611062-1999-11e5-9b05-aba9e65b46c2.png)

**Comment by EJWagenmakers** [comment] 2015-06-23 09:21
This recompute for "additional info" is also present in the Bayesian correlation test.

**Comment by jonathon-love** [comment] 2015-06-23 14:21
duplicate of #727

**Closed** 2015-06-25 17:10 UTC
Labels: duplicate

**Comment by quentingronau** [comment] 2015-07-13 13:33
Hi,

With the latest commit, I fixed the issues mentioned in #727 which are part of this issue. However, if additional info is selected, a new plot is still made, because, at the moment, I do not know how to put new information in an existing plot (the margin sizes change, the pizza plot is drawn, etc.). That is why I make a new plot/png when the user wants to see additional info.

Cheers,
Quentin

**Comment by EJWagenmakers** [comment] 2015-07-13 21:38
OK!

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************
