### ISSUE TITLE
Dummy Coding for Linear Regression Analysis

### ISSUE THREAD

**Issue by neurotroph** [jasp-stats/jasp-desktop#1260] opened 2016-03-24 08:11 UTC
From what I have seen, Linear Regression Analysis in JASP only supports metric covariates/predictors. Automatic dummy coding for categorial variables would be a great feature. A further option to select different types of coding (dummy, effect, ...).

R does this, from what I know, automatically when using factors() in a data.frame.

Any plans on adding this in the future?

**Comment by philippberens** [comment] 2016-05-04 12:23
I agree - that would be nice. In particular, since this already seems to be implemented for the log-linear model.

**Comment by lindeloev** [comment] 2017-09-11 21:49
This is a duplicate of https://github.com/jasp-stats/jasp-desktop/issues/902. I also want to cast my vote for this in both Bayesian and Linear regression.

**Comment by AlexanderLyNL** [comment] 2018-06-19 17:20
Use ANCOVA for this purpose instead.

**Closed by AlexanderLyNL** 2018-06-19 17:20 UTC
Labels: Layer: R, Priority 2: Medium, Type: Enhancement

**Comment by carlosquintanillaa** [comment] 2018-08-10 21:17
I cast my vote for this improvement. The minute you can create dummy variables inside JASP I'll adopt JASP for my Stat Course. Most real datasets are a combination of continuous and categorical variables. We need them for both Linear Regression and Logistic Regression. Currently I use Gretl in my courses.
