### ISSUE TITLE
Support for HiDPI screens

### ISSUE THREAD

**Issue by Santihago** [jasp-stats/jasp-desktop#676] opened 2015-05-27 10:20 UTC
Hello,

I am using a Dell XPS with a  3200 x 1800 resolution screen, and sadly JASP looks too tiny and some features are unusable. 

With most apps not ready for high resolution screens, Windows automatically rescales them (making them blurry). But this is not the case here, the rescaling is not happening for some reason.

I am using JASP 0.6.6 64-bit on Windows 8.1. I am attaching two screenshots, one comparing size to SPSS and another showing how some features are unusable.

It would be nice to have it working on HiDPI screens. Thank you!
![screenshot 55](https://cloud.githubusercontent.com/assets/12624977/7833898/4b9352c2-0462-11e5-8cb0-23f376ba1fdd.png)
![screenshot 58](https://cloud.githubusercontent.com/assets/12624977/7833897/4b9291c0-0462-11e5-89a5-6ecd3ba93153.png)

**Comment by jonathon-love** [comment] 2015-05-27 14:53
haha, oh wow. we've seen this before, but your screenshots are awful! :P

we're working on it, but it's proving a difficult issue to solve. will hopefully have something in the coming weeks.

duplicate of #538

**Closed** 2015-05-27 14:53 UTC
Labels: duplicate

**Comment by Santihago** [comment] 2015-05-27 15:19
Sorry for the duplicate. Thanks for answering and good luck on solving the problem, I'm very excited about your software.

**Comment by jonathon-love** [comment] 2015-05-27 20:56
not a worry! it's still good for us to see how bad JASP can look on some of these displays.

thanks for your report.
