### ISSUE TITLE
Version 8.3.0 Logistic Regression in Ubuntu 16.04. When the depedent variabele is selected a read error message appears . This problam does not appear in Windows.

### ISSUE THREAD

**Issue by WillemVlakveld** [jasp-stats/jasp-desktop#2058] opened 2017-10-14 05:55 UTC
## Template for bug reports

* JASP version:
* OS name and version:
* Analysis:
* Steps to reproduce: 

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by vankesteren** [comment] 2017-10-16 20:52
Sorry, this is not enough information for us to identify the problem. Could this be a duplicate of #2060? 

If not, could you provide more info (e.g., screenshot, steps to reproduce)

Thanks!

**Comment by vankesteren** [comment] 2017-11-22 09:51
I'm closing this due to lack of response, we can reopen if the requester responds!

**Closed by vankesteren** 2017-11-22 09:51 UTC
Labels: Wait For Requester
