### ISSUE TITLE
Logistic Regression Analysis Terminated Unexpectedly - Windows (0.8.3.1)

### ISSUE THREAD

**Issue by rsgns** [jasp-stats/jasp-desktop#2060] opened 2017-10-16 09:07 UTC
* JASP version: 0.8.3.1
* OS name and version: Windows 10
* Analysis: Logistic Regression

Hi! I am in the middle of a logistic regression analysis with my boss and when adding the dependent variable for the analysis this message appears [https://i.imgur.com/2LIoe20.png](url) and I was wondering for possible solutions. Our dependent variable is a nominal data derived from excel OSD file, and wonder if it's the format we use (as our we wondered if it was the headers causing the issue as that was the "on treatment" field mentioned. 

Thank you for your time to help us! It's greatly appreciated. 
![logistic](https://user-images.githubusercontent.com/32834848/31604002-7fe56104-b294-11e7-879e-4960d7040233.PNG)

**Comment by akashrajkn** [comment] 2017-10-16 15:53
@rsgns thank you for reporting the issue. We will fix this as soon as possible. (i believe it is because of the space in the column header)

**Comment by vankesteren** [comment] 2017-10-16 20:50
Confirmed that this is in the space of the column header! In the upcoming release this will be fixed. For the time being, I suggest renaming your column to `On_treatment`. Sorry for the inconvenience!

**Comment by rsgns** [comment] 2017-10-17 00:54
Hi JASP team,

No worries, had a feeling it was the header too haha. Thank you all very
much for your swift response, its very encouraging to see such effort and
it is truly appreciated. Have promoted your software across my campus and
will be spreading the word more!

Keep up the good work and never stop giving your best, we acknowledge and
appreciate all the efforts you guys do. All the best moving forward!

Regards
Russell

**Comment by rsgns** [comment] 2017-10-17 05:59
Hi, an update for your team :)

We managed to get the logistic regression analysis working, however we were only able to do our analysis after changing the headers to one word codes (eg Teen Youth = TNYTH). underlined spacing did not work and also produced errors similar to what we posted yesterday.

Thanks for the help, it's greatly appreciated!

**Comment by vankesteren** [comment] 2017-10-17 07:34
Thanks for the great feedback and words of encouragement!

**Comment by vankesteren** [comment] 2017-11-22 09:50
This is fixed in 0.8.4!

**Closed by vankesteren** 2017-11-22 09:50 UTC
Labels: Difficulty 3: Easy, Layer: R, Priority 1: High, Type: Bug
