### ISSUE TITLE
Contingency table only lists row factor (omits column factor)

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#569] opened 2015-04-09 08:17 UTC
The contingency tables only list the row factor. For instance, in the screenshot the only factor show in "doll"; however, the other factor, "child", is not shown.
E.J.
![image](https://cloud.githubusercontent.com/assets/8603015/7062848/84ef55fc-dea1-11e4-8f5a-e8fbbd9317a0.png)

**Comment by jonathon-love** [comment] 2015-04-09 09:17
duplicate of #324

**Closed by jonathon-love** 2015-04-09 09:17 UTC
