### ISSUE TITLE
B-Correlation Matrix plot - One-Sided broken

### ISSUE THREAD

**Issue by AlexanderLyNL** [jasp-stats/jasp-desktop#616] opened 2015-04-18 08:48 UTC
Hi Quentin, 

There's something wrong with the one-sided matrix plot. Could you have a look? 

@quentingronau 
![screen shot 2015-04-18 at 10 40 09](https://cloud.githubusercontent.com/assets/10271675/7214714/3c35b8d8-e5b8-11e4-9d8b-4a596b0b4d5c.png)

**Comment by quentingronau** [comment] 2015-04-18 09:02
Hi Alexander,

I tried to reproduce it, but recognized that I have a slightly different Big Five data set (see below). Could you maybe send me the one that you used so I can try to find the error? I also recognized that your output table says "Pearson's r" and my output says "Pearson's R". Did you already commit this, so that I should do a rebase?

![bayesiancorrelation18042015](https://cloud.githubusercontent.com/assets/8697436/7214762/5b74253e-e5ba-11e4-97b5-ff6b65b1d9d1.png)

**Comment by AlexanderLyNL** [comment] 2015-04-18 09:13
Yes I’ve committed a new code. First, I changed alpha’s into kappa’s. In essence, alpha is a precision and kappa is a width. Furthermore, I put the estimation of the beta distribution all together into one function, see your code neer aParameter.

**Comment by AlexanderLyNL** [comment] 2015-04-18 09:14
So please retain your code before rebasing, as somewhere something went wrong.

**Comment by AlexanderLyNL** [comment] 2015-04-18 09:18
Moreover, could you change the prior plots in correlationBayesianPairs.R as the prior should change with Beta*prior width (this is kappa) 

hence, kappa=options$priorWidth

**Comment by quentingronau** [comment] 2015-04-18 09:52
Hi Alexander,

I did a rebase and now the Bayesian Correlation does not produce any output, but an error message, do you have an idea what my problem might be?
(My computer is relatively sensitive to rebasing, so it can be that your code is perfectly fine, but something went wrong with the rebasing, maybe I should ask Jonathon instead)

![2_bayesiancorrelation18042015](https://cloud.githubusercontent.com/assets/8697436/7214935/5d2a05ae-e5c1-11e4-9aa7-64abe5e37cfc.png)

**Comment by AlexanderLyNL** [comment] 2015-04-18 09:56
it’s a typo in 

.excludePairwiseCorData <- function(v1, v2){
	# To exclude the data pairwise
	#
	screened.data <- list(v1=v1, v2=v2)
		
	remove.index.1 <- which(is.na(v1))
	remove.index.2 <- which(is.na(v2))
	remove.index <- unique(c(remove.index.1, remove.index.2))
	if (length(remove.index) > 0){
		screened.data$v1 <- v1[-(remove.index)]
		screened.data$v2 <- v2[-(remove.index)]
	}
	
	return(screened.data)
}

I’ve committed it. You can change it manually if you can’t wait

**Comment by jonathon-love** [comment] 2015-04-18 09:57
merged.

**Comment by quentingronau** [comment] 2015-04-18 10:15
Hm,

On my laptop the one-sided test still works (I assume you used prior width = 2?)

![3_bayesiancorrelation18042015](https://cloud.githubusercontent.com/assets/8697436/7215021/99243784-e5c4-11e4-8fdf-354f22ad935e.png)

**Comment by AlexanderLyNL** [comment] 2015-04-18 21:24
No idea why, but it’s not working at my end. Good to know that it’s working on your laptop. I’ll try again on my mac at work.

**Comment by boutinb** [comment] 2016-08-10 15:35
This issue is closed due to too long inactivity. Please re-open this issue is this problem still occurs.

**Closed by boutinb** 2016-08-10 15:35 UTC
