### ISSUE TITLE
Descriptive Plots Gone Wrong in 0.9.1

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2850] opened 2018-10-12 11:17 UTC
@koenderks @vandenman @AlexanderLyNL  

Take the Adam Sandler data set, go to Descriptives, and select Correlation Plot. The old version looked pretty, the new version is not usable. This is a high-priority issue, as far as I'm concerned.
![correlationplotadamsandlerold](https://user-images.githubusercontent.com/8603015/46866245-e3261800-ce20-11e8-8b01-08baa979a24f.png)
![correlationplotadamsandlernew](https://user-images.githubusercontent.com/8603015/46866249-e7523580-ce20-11e8-9e27-554c33e73f79.png)

Side note: it does look *much better* on Quentin's laptop (Mac), but still far from ideal. 
E.J.

**Comment by lindeloev** [comment] 2018-10-12 11:46
This is what it looks like with two continuous variables and a nominal one. It cuts the right edge of the plot a bit too early and the plotted error/info also extends beyond the borders. 

Windows10 with JASP 9.1 on 1920 x 1080 resolution.

![image](https://user-images.githubusercontent.com/1439417/46867323-ea4f2500-ce24-11e8-8cb5-0220e3a4bddc.png)

**Comment by AlexanderLyNL** [comment] 2018-10-12 12:03
We're struggling with this plot a bit. A suboptimal solution now is to use the correlation plot under linear regression - correlation instead. Nonetheless, I'll discuss this with the relevant people.

**Comment by vandenman** [comment] 2018-10-18 08:18
This issue should have been fixed with #2855

**Closed** 2018-10-18 08:33 UTC
