### ISSUE TITLE
JASP no longer running analyses on Windows 7 64bit

### ISSUE THREAD

**Issue by BPaton** [jasp-stats/jasp-desktop#1687] opened 2017-03-17 10:42 UTC
* JASP version: 0.8.1 and many previous versions
* OS name and version: Windows 7 64 bit Enterprise
* Analysis:  I have a Windows 7 64 bit box that has had many previous versions of JASP installed, all of them working. The most recent was a version I downloaded in November last year. I have also just recently downloaded the most recent version. Since trying to run JASP today, using the previous version and the most recent version, and uninstalling and trying every version I have back to 0.7.5 Beta 2 I have been able to open JASP and open datasets but any analysis I select or run does nothing. This also includes running JASP from various zipped installations. Given the machine in question is domain managed by my employer (a university) but I have admin rights I have tried some troubleshooting but to no avail. I have also tried re-opening previous saved JASP analysis files and tried to add further analyses or modify existing ones also to no avail. This issue is quite frustrating and suspect it might be either machine specific or perhaps related to the fact it is in a managed domain. Are there files or registry entries that might be left behind even after your uninstall JASP?

This problem is specific to my work PC it seems as my home PC still runs JASP fine. I also checked the Windows Event logs for anything odd going on an nothing correlated with the running of JASP came up.

Thanks.

Bryan.

**Comment by boutinb** [comment] 2017-03-22 08:29
@BPaton This is indeed quite frustrating. We have a couple of this kind of issues on Windows 7. But we cannot get a grip to what is going on. We cannot reproduce it on our Windows 7 Enterprise machine with an admin or even a normal user.
We are going to make a debug version of the last version for Windows. When it is ready, you can install it, and hopefully it can gives more log about what is going on.

**Comment by BPaton** [comment] 2017-03-22 09:36
Thanks the debug version sounds good. Really want to figure this out as I was planning on using JASP for teaching in about two months time.

**Comment by boutinb** [comment] 2017-03-23 10:58
@BPaton Can you install the debug version http://static.jasp-stats.org/JASP-0.8.1.1-Setup-Debug.exe
Then go to Program Files\JASP-0.8.1.1 and start JASP from the command line in this way:
. JASP.exe > %TEMP%\log.txt
I am curious what the log.txt will say.

**Comment by BPaton** [comment] 2017-04-12 05:38
Thanks, finally had chance to get back to the machine. JASP will now not even load. I get a MSVC++ runtime error "This application has requested the Runtime to terminate it in an unusual way" (original wording). I then get a typical Windows mini dump dialog. I have saved the mini dump and associated files. The log.txt file is of course empty. The mini dump is 9 MB compressed so I have attached everything in a zip here.

Thanks.

[JASP errors.zip](https://github.com/jasp-stats/jasp-desktop/files/915487/JASP.errors.zip)

**Comment by BPaton** [comment] 2017-04-12 07:04
I can install and run JASP 0.8.1.1 and not get the MSVC run time errors but the analyses still fail to run.

**Comment by boutinb** [comment] 2017-04-18 10:17
@BPaton I see in the dump that you use Saphos virus scanner. Can you switch it off before launching JASP?

**Comment by BPaton** [comment] 2017-04-18 10:19
Hi @boutinb I can turn off Sophos but only on my own office machine on which I have admin privileges. I will not be able to turn it off on the machines in the computer lab in which I will be doing teaching (with JASP) in. Odd though as Sophos has been running the whole time, previously when it worked and now.

**Comment by boutinb** [comment] 2017-04-18 11:06
If I understand well, JASP was working on your lab computer last year, and now by installing the new or even the old versions of JASP, it does not work. Even zipped version does not work. So I cannot think that it is a registry problem (you can still check it with regedit). And if the old versions of JASP were working, and not now anymore, it is not a problem in JASP self (at least not only). So there are new tools, utilities installed on the lab machine that must hinder JASP doing the analyses. I have once seen that a Virus scanner was the problem. 
I see also from the dump that JASP runs with AMinit64.dll, and from this (https://support.symantec.com/en_US/article.TECH223694.html), I can see that Application metering is on on this machine. It would be also a good test to tun JASP without it.
Another check would be also to use depedencywalker (http://www.dependencywalker.com/). You can try to run it with JASP.exe and JASPEngine.exe, and check what it says...
It is a really annoying problem, but as I cannot reproduce it, I can only have wild guess...

**Comment by BPaton** [comment] 2017-04-18 11:10
No problems, thanks for giving me some avenues to chase up. Will let you know what I find.

**Comment by BPaton** [comment] 2017-04-24 03:46
Apologies for the run around it seems whatever issue it was preventing the operation has now been fixed, a number of group policy and Windows updates were recently applied and I am hoping that has fixed the issue. I still need to test it on a machine that I do not have admin rights on.

**Comment by boutinb** [comment] 2017-05-01 09:10
That's good news! Only thing is that we don't really know what exactly was going wrong... Tell me whether this problem does not occur with a not-admin user.

**Comment by patwms** [comment] 2017-06-05 17:09
I have the same set-up as Bryan (Windows 7 Enterprise 64 bit) and I'm having the same problem. I just downloaded 0.8.1.2 and everything seems to work until I click OK to run an analysis, then nothing. Also like Bryan, I've had earlier versions on this machine and they also wouldn't work.

Have you learned anything more since his problem resolved itself?

Would it help for me to run a debug version for 0.8.1.2, as you had him do?

Thanks,
Pat

**Comment by boutinb** [comment] 2017-06-14 10:04
@patwms Did you try the ZIP version (http://static.jasp-stats.org/JASP-0.8.1.2-64-bit.zip)?

**Comment by patwms** [comment] 2017-06-14 13:29
My situation is even more like Bryan's than I reported earlier. His problem
seemed almost to "resolve itself." The same thing has happened here. This
is not the first time that JASP, various installations, has not worked for
a while and then, for no obvious reason, does work. I have to conclude that
the problem does not lie with JASP.

**Comment by AlexanderLyNL** [comment] 2017-06-14 13:33
Hi Pat,

Happy to hear that the problem resolved itself and thanks for informing us about this. As both users' problem resolved itself, I'll close this issue. 

Cheers,
Alexander

**Closed by AlexanderLyNL** 2017-06-14 13:33 UTC
Labels: OS Windows, Type: Bug, Wait For Requester

**Comment by boutinb** [comment] 2017-06-14 13:35
@patwms Fine that it works again ! But if you have any hint whatsoever why JASP did not work, please tell me! This problem occurred few times, and it is quite frustrating not to be able to help.
