### ISSUE TITLE
Error on adding simple contrast in repeated measures ANOVA

### ISSUE THREAD

**Issue by mvgorcum** [jasp-stats/jasp-desktop#2432] opened 2018-03-21 19:19 UTC
* JASP version: 0.8.5.1
* OS name and version: Both Kubuntu 16.04.4 and KDE neon user edition (based on ubuntu 16.04)
* Analysis: repeated measures anova
* Steps to reproduce: 

After opening the attached file and choosing repeated measures anova I name the two within subjects variables (both have three levels) and adding the data to the cells, and I add the between subject factor (gender in this case).

After that I try to choose a simple contrast, and I get the following error:

```
This analysis terminated unexpectedly.

Error in if (is.finite(value)) {: argument is of length zero

Stack trace
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)

.rmAnovaContrastTable(options, perform, status, stateContrasts)

.clean(as.numeric(result$estimate[i]))
```
[LooksOrPersonality.zip](https://github.com/jasp-stats/jasp-desktop/files/1834846/LooksOrPersonality.zip)

**Comment by JohnnyDoorn** [comment] 2018-03-22 11:14
Hi Mvgorcum,
Unfortunately I cannot reproduce your error on Ubuntu 16.04. What version of the R-package lsmeans/afex do you have? The lsmeans package has recently been replaced by emmeans by it's developers and is causing some errors for some Linux users at the moment. However, the issue with this package will be fixed in the next release. However, I'm not sure whether this is relevant at the moment, because the error you are seeing is not like the error we have seen before related to lsmeans. 
Kind regards,
Johnny

**Comment by mvgorcum** [comment] 2018-03-22 11:17
Hi Johnny,

Thanks for the reply.
I have the following versions installed:
```
r-cran-lsmeans:
  Installed: 2.27-61-1cran1ppa0

r-cran-afex:
  Installed: 0.15-2-1
```

**Comment by JohnnyDoorn** [comment] 2018-03-22 14:44
Hi Mathijs,
Can you try installing JASP through flatpak? This is the new way JASP will be distributed to Linux users, since it generalizes a lot better to different Linux distributions, and can contain it's own packages, rather than users' local packages. The latest flatpak version should also include the fix the issue I mentioned in my previous post.
Instructions for installing JASP through flatpak can be found here: https://jasp-stats.org/download/
If updating does not fix your contrast issue, please let me know!
Cheers,
Johnny

**Comment by mvgorcum** [comment] 2018-03-22 14:55
I did try JASP using flatpak but it errored out much earlier with an error message that looked more nasty. (then again I never got flatpak to work very nicely with ubuntu and KDE)

I'll try upgrading my ubuntu version first and install 0.8.6 and report back if that fixed the issue.  

If I find the time I'll install the flatpak version again and report the error (if that happens).

Thanks for your time!

**Comment by mvgorcum** [comment] 2018-03-22 18:07
I just made a clean install of kubuntu 17.10, added the rstudio repo (because I also use R separately) and the jasp ppa and I run in to the same bug. This time on jasp 0.8.6

**Comment by JohnnyDoorn** [comment] 2018-03-23 10:12
Hmm that's unfortunate - can you make a screenshot of the error message? 
Thanks for your help!

**Comment by mvgorcum** [comment] 2018-03-23 11:06
Attached.

![image](https://user-images.githubusercontent.com/24435423/37826123-2d3449c6-2e8a-11e8-80a6-42813ea0dc92.png)

**Comment by mvgorcum** [comment] 2018-03-26 21:44
On a whim I decided to try to run JASP in docker to solve this issue, and that worked. I used an ubuntu 17.10 base, so the error is probably somewhere in the KDE/QT packages.

**Comment by JohnnyDoorn** [comment] 2018-03-28 11:01
Hi Mathijs,
Thanks for the update! I haven't been able to look at this issue further, as it's a bit outside of my programming range, but maybe @JorisGoosen or @boutinb have a use for the dockerfile to identify what is going on.
I'm glad that it works now though!
Cheers,
Johnny

**Comment by JorisGoosen** [comment] 2018-03-28 12:15
Sounds like maybe there was a mismatch between the R-libs used for JASP and the ones that @mvgorcum took from Rstudio-repo. That would explain why a local install of 17.10 doesn't and a docker-install does work I think.

**Comment by mvgorcum** [comment] 2018-03-28 13:07
Sounds plausible. Is there a way for me to find out which R libs are (/is) the culprit? While running in a container works, I'd rather use a normally installed version.

**Comment by JorisGoosen** [comment] 2018-03-28 13:31
Well, the ubuntu deb-package depends on the following r-packages: `r-base-core, r-cran-rcpp, r-cran-rinside, r-cran-bayesfactor, r-cran-lme4, r-cran-afex, r-cran-car, r-cran-effects, r-cran-logspline, r-cran-lsmeans, r-cran-plotrix, r-cran-rjson, r-cran-vcd, r-cran-vcdextra, r-cran-ggplot2, r-cran-hypergeo` seeing if any of these are installed from the rstudio-repo would be a good start.

But it could be that rstudio-repo install their own version of R somewhere and changes R_HOME to some value other than the one of the ubuntu-R. I guess this could be checked by trying `echo $R_HOME` in the terminal.

**Comment by mvgorcum** [comment] 2018-03-28 23:15
Running from console gave a long list of messages of "Package <something> not installed!" which prompted me to install those packages through R. This did remove all the "not installed" messages, though there is still a list of packages that have an "<package> is not the correct version;" error.  
Other than that I only get "NOTE: Results may be misleading due to involvement in interactions", which seems expected and unrelated.  
This didn't solve my problem.

All the r-packages you mentioned are installed from the ubuntu repo, except `r-base-core` which is installed from an r-project.org mirrror, and installed as version `r-base-core-dbg_3.4.4-1artful0` while the ubuntu package is `3.4.2`. Because I also use R separately and installing 3.4.2 instead caused all kinds of other dependency problems for me I decided not to try on my main machine.

I did, however, run a live install of kubuntu 17.10, added only the jasp PPA, and installed jasp there, resulting in the same issue.

Also on my kde neon install (based on ubuntu xenial with KDE plasma) I get the same error, while I never installed any R packages or repos there. (note that the kde neon version is 0.8.5.1 while the kubuntu pc uses 0.8.6).

Based on this my best guess is that it has to do with some KDE/QT package, which would be solved by my docker container, because it uses a plain ubuntu as base. Unfortunately the docker container has a few small glitches (mostly graphical).

**Comment by JorisGoosen** [comment] 2018-03-29 14:33
Hmm, it just seems weird to me that this happens because of Qt/KDE because it seems to occur in an analysis..

I will have to check it out in a VM or something to see if I can trigger it and if the live kubuntu 17.10 already has the problem that should be easy enough. Ill get back to you when I have the time to do that!

**Comment by AlexanderLyNL** [comment] 2018-10-11 19:50
I just tried this with 0.9.1 and everything seems to work fine. Please reopen if this is not the case for you. 

[LooksOrPersonality.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/2470477/LooksOrPersonality.jasp.zip)

**Closed by AlexanderLyNL** 2018-10-11 19:50 UTC

**Comment by mvgorcum** [comment] 2018-10-11 22:39
I just tested it and indeed the error is gone. Thanks for looking in to it.
