### ISSUE TITLE
Summary Kendall: no package called "SuppDists"

### ISSUE THREAD

**Issue by lindeloev** [jasp-stats/jasp-desktop#2480] opened 2018-04-19 22:24 UTC
In summary statistics, I tried calculating a BF for Kendall's tau_b = 0.37. Works fine for N >= 50, but fails for N < 50 with

```
This analysis terminated unexpectedly.

Error in loadNamespace(name): there is no package called ‘SuppDists’

Stack trace
.calculateBF.summarystats.correlation(options = options, state = state, diff = diff)

.pValueFromCor(corrie = some.r, n = some.n, method = 'kendall')

SuppDists::pKendall

getExportedValue(pkg, name)

asNamespace(ns)

getNamespace(ns)

tryCatch(loadNamespace(name), error = function(e) stop(e))

tryCatchList(expr, classes, parentenv, handlers)

tryCatchOne(expr, names, parentenv, handlers[[1]])

value[[3]](cond)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports
```

![image](https://user-images.githubusercontent.com/1439417/39021473-2bc22aba-4431-11e8-886c-3760b353a2bc.png)

**Comment by lindeloev** [comment] 2018-04-19 22:37
Forgot to mention: JASP 8.5.1 on Ubuntu 16.04. Maybe everything's just too old and I should upgrade to the newest Ubuntu when it comes out? :-)

**Comment by akashrajkn** [comment] 2018-04-20 09:29
I got the same error as well. I reinstalled `SuppDists` and the analysis runs fine. I'll check out why this is happening.

**Comment by AlexanderLyNL** [comment] 2018-04-21 19:33
The problem is due to the use of SuppDists to calculate the p-value when n < 50: 
- n < 50 regime: Given tau use the exact sampling from SuppDists to calculate the p-value
- n >= 50 regime: Given tau use an approximate normal distribution to calculate the p-value. 

The reason for doing so is for consistency. I mimicked the behaviour of cor.test, which also uses these two regimes. In other words, the p-values from cor.test are approximations to ones derived from SuppDists when n >= 50. @akashrajkn can you figure out why SuppDists wasn't installed properly?

**Comment by akashrajkn** [comment] 2018-04-23 08:48
Yup, I'll look into it.

**Comment by AlexanderLyNL** [comment] 2018-10-11 20:04
This should be fixed when we incorporated the versions of the packages into the flatpak build. Please reopen if the problem reappears. 

https://jasp-stats.org/linux-installation-guide/

**Closed by AlexanderLyNL** 2018-10-11 20:04 UTC
